# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'window.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QRadioButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1046, 804)
        palette = QPalette()
        brush = QBrush(QColor(37, 13, 66, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(247, 246, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(46, 55, 48, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush2)
        brush3 = QBrush(QColor(78, 77, 77, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush3)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush4 = QBrush(QColor(120, 120, 120, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet(u"background-color:rgb(247, 246, 255)")
        self.help_action = QAction(MainWindow)
        self.help_action.setObjectName(u"help_action")
        self.plus_images = QAction(MainWindow)
        self.plus_images.setObjectName(u"plus_image")
        self.out_action = QAction(MainWindow)
        self.out_action.setObjectName(u"out_action")
        self.action_S = QAction(MainWindow)
        self.action_S.setObjectName(u"action_S")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Load_botton = QPushButton(self.centralwidget)
        self.Load_botton.setObjectName(u"Load_botton")
        self.Load_botton.setGeometry(QRect(800, 40, 190, 46))
        palette1 = QPalette()
        brush5 = QBrush(QColor(255, 255, 255, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        self.Load_botton.setPalette(palette1)
        font = QFont()
        font.setFamilies([u"\ud568\ucd08\ub86c\ub3cb\uc6c0"])
        self.Load_botton.setFont(font)
        self.Load_botton.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        icon = QIcon()
        icon.addFile(u"../../../../photoshop/folder.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Load_botton.setIcon(icon)
        self.Load_botton.setAutoDefault(False)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(530, 100, 461, 301))
        palette2 = QPalette()
        brush6 = QBrush(QColor(231, 229, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush6)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush6)
        self.groupBox.setPalette(palette2)
        font1 = QFont()
        font1.setFamilies([u"\ud568\ucd08\ub86c\ub3cb\uc6c0"])
        font1.setPointSize(9)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setUnderline(False)
        self.groupBox.setFont(font1)
        self.groupBox.setStyleSheet(u"background-color: rgb(231, 229, 255);\n"
"font: 9pt \"\ud568\ucd08\ub86c\ub3cb\uc6c0\";\n"
"")
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 50, 241, 241))
        self.groupBox_2.setStyleSheet(u"\n"
"background-color: rgb(254, 253, 255);")
        
        #1: 사진 반전 2: 모자이크 사진 3: 볼록렌즈 4:오목렌즈 5:흐린이미지 6:HSV사진 11:색반전 12: 사진 합치기
        self.flipButton = QRadioButton(self.groupBox_2)
        self.flipButton.setObjectName(u"radioButton")
        self.flipButton.setGeometry(QRect(80, 40, 141, 28))
        self.flipButton.setCursor(QCursor(Qt.OpenHandCursor))
        self.mozaicButton= QRadioButton(self.groupBox_2)
        self.mozaicButton.setObjectName(u"radioButton_2")
        self.mozaicButton.setGeometry(QRect(40, 80, 181, 28))
        self.mozaicButton.setCursor(QCursor(Qt.OpenHandCursor))
        self.polarButton = QRadioButton(self.groupBox_2)
        self.polarButton.setObjectName(u"radioButton_3")
        self.polarButton.setGeometry(QRect(40, 120, 191, 28))
        self.polarButton.setCursor(QCursor(Qt.OpenHandCursor))
        self.scaleButton = QRadioButton(self.groupBox_2)
        self.scaleButton.setObjectName(u"scaleButton")
        self.scaleButton.setGeometry(QRect(40, 160, 191, 28))
        font2 = QFont()
        font2.setFamilies([u"\ud568\ucd08\ub86c\ub3cb\uc6c0"])
        font2.setPointSize(9)
        font2.setBold(False)
        font2.setItalic(False)
        self.scaleButton.setFont(font2)
        self.scaleButton.setCursor(QCursor(Qt.OpenHandCursor))
        self.blurButton= QRadioButton(self.groupBox_2)
        self.blurButton.setObjectName(u"blurButton")
        self.blurButton.setGeometry(QRect(60, 200, 168, 28))
        self.blurButton.setCursor(QCursor(Qt.OpenHandCursor))
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(270, 50, 171, 131))
        self.groupBox_4.setStyleSheet(u"background-color: rgb(254, 253, 255);\n"
"")
        self.paintButton = QRadioButton(self.groupBox_4)
        self.paintButton.setObjectName(u"paintButton")
        self.paintButton.setGeometry(QRect(50, 40, 111, 28))
        self.paintButton.setCursor(QCursor(Qt.OpenHandCursor))
        self.hsvButton = QRadioButton(self.groupBox_4)
        self.hsvButton.setObjectName(u"hsvButton")
        self.hsvButton.setGeometry(QRect(30, 80, 141, 28))
        self.groupBox_5 = QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(270, 200, 171, 91))
        self.groupBox_5.setStyleSheet(u"background-color: rgb(254, 253, 255);\n"
"")
        self.plusButton = QRadioButton(self.groupBox_5)
        self.plusButton.setObjectName(u"plusButton")
        self.plusButton.setGeometry(QRect(10, 50, 168, 28))
        self.plusButton.setCursor(QCursor(Qt.OpenHandCursor))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 100, 461, 301))
        self.label.setFont(font)
        self.label.setStyleSheet(u"\n"
"border-right-color: rgb(98, 98, 98);\n"
"background-color: rgb(244, 244, 244);")
        self.Save_button = QPushButton(self.centralwidget)
        self.Save_button.setObjectName(u"Save_button")
        self.Save_button.setGeometry(QRect(800, -10, 188, 46))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Button, brush5)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush5)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        self.Save_button.setPalette(palette3)
        self.Save_button.setFont(font)
        self.Save_button.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        icon1 = QIcon()
        icon1.addFile(u"../../../../photoshop/arrow.png", QSize(), QIcon.Normal, QIcon.Off)
        self.Save_button.setIcon(icon1)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(18, 18, 707, 81))
        self.lineEdit = QLineEdit(self.groupBox_3)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(40, 10, 641, 51))
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet(u"background-color: rgb(230, 243, 255);")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 410, 461, 301))
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"background-color: rgb(232, 232, 232);")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(530, 410, 461, 301))
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(u"background-color: rgb(211, 209, 211);")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1046, 38))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_O = QMenu(self.menubar)
        self.menu_O.setObjectName(u"menu_O")
        self.menu_H = QMenu(self.menubar)
        self.menu_H.setObjectName(u"menu_H")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_O.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())
        self.menu.addAction(self.plus_images)
        self.menu_O.addAction(self.out_action)
        self.menu_H.addAction(self.action_S)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.help_action.setText(QCoreApplication.translate("MainWindow", u"\uc0c9\uc0c1 \ubc18\uc804(P", None))
#if QT_CONFIG(tooltip)
        self.help_action.setToolTip(QCoreApplication.translate("MainWindow", u"\ub3c4\uc6c0\ub9d0 \ubcf4\uae30", None))
#endif // QT_CONFIG(tooltip)
        self.plus_images.setText(QCoreApplication.translate("MainWindow", u"\ub354\ud560 \uc774\ubbf8\uc9c0 \ubd88\ub7ec\uc624\uae30(A)", None))
#if QT_CONFIG(shortcut)
        self.plus_images.setShortcut(QCoreApplication.translate("MainWindow", u"A", None))
#endif // QT_CONFIG(shortcut)
        self.out_action.setText(QCoreApplication.translate("MainWindow", u"\uc0c8\ub85c\uace0\uce68(T)", None))
#if QT_CONFIG(shortcut)
        self.out_action.setShortcut(QCoreApplication.translate("MainWindow", u"T", None))
#endif // QT_CONFIG(shortcut)
        self.action_S.setText(QCoreApplication.translate("MainWindow", u"\ubcf4\uae30(S)", None))
#if QT_CONFIG(shortcut)
        self.action_S.setShortcut(QCoreApplication.translate("MainWindow", u"S", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.Load_botton.setToolTip(QCoreApplication.translate("MainWindow", u"\uc0ac\uc9c4 \ubd88\ub7ec\uc624\uae30", None))
#endif // QT_CONFIG(tooltip)
        self.Load_botton.setText(QCoreApplication.translate("MainWindow", u"Load_image", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\uae30\ub2a5", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\uc0ac\uc9c4 \uae30\ub2a5", None))
        self.flipButton.setText(QCoreApplication.translate("MainWindow", u"\uc0ac\uc9c4 \ubc18\uc804", None))
        self.mozaicButton.setText(QCoreApplication.translate("MainWindow", u"\ubaa8\uc790\uc774\ud06c \uc0ac\uc9c4", None))
        self.polarButton.setText(QCoreApplication.translate("MainWindow", u"\ubcfc\ub85d\ub80c\uc988 \ud6a8\uacfc", None))
        self.scaleButton.setText(QCoreApplication.translate("MainWindow", u"\uc624\ubaa9\ub80c\uc988 \ud6a8\uacfc", None))
        self.blurButton.setText(QCoreApplication.translate("MainWindow", u"\ud750\ub9b0 \uc774\ubbf8\uc9c0", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"\uc0c9\uc0c1 \uae30\ub2a5", None))
        self.paintButton.setText(QCoreApplication.translate("MainWindow", u"\uc0c9 \ubc18\uc804", None))
        self.hsvButton.setText(QCoreApplication.translate("MainWindow", u"HSV \uc0ac\uc9c4", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"\ub354\ud558\uae30 \uae30\ub2a5", None))
        self.plusButton.setText(QCoreApplication.translate("MainWindow", u"\uc0ac\uc9c4 \ud569\uce58\uae30", None))
        self.label.setText("")
        self.Save_button.setText(QCoreApplication.translate("MainWindow", u"Save_image", None))
        self.groupBox_3.setTitle("")
        self.lineEdit.setText(QCoreApplication.translate("MainWindow", u"                    \uc774\uc9c0- \uc2ec\ud50c- \ud3ec\ud1a0\uc0f5 \uc791\uc740 \uba54\ubaa8\uc7a5", None))
        self.label_3.setText("")
        self.label_5.setText("")
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\ub354\ud560 \uc774\ubbf8\uc9c0 \ubd88\ub7ec\uc624\uae30", None))
        self.menu_O.setTitle(QCoreApplication.translate("MainWindow", u"\uc0c8\ub85c\uace0\uce68", None))
        self.menu_H.setTitle(QCoreApplication.translate("MainWindow", u"\ub3c4\uc6c0\ub9d0", None))
    # retranslateUi

